---
- hosts: all
  tasks:
  - name: Copy host file
    copy: 
      src: ./hostfile
      dest: /etc/hosts
  - name: Copy ambari.repo file
    copy: 
      src: ./ambari.repo
      dest: /etc/yum.repos.d/ambari.repo
